service: example-update-aws-lambda-fast
frameworkVersion: '2'

functions:
  index:
    handler: dist/index.handler
    events:
      - httpApi: "GET /"

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ap-northeast-1
  memorySize: 128
  timeout: 10
  logRetentionInDays: 30
  deploymentBucket: b1ec0be3-01c8-438a-817f-710e84866464
  versionFunctions: false
  lambdaHashingVersion: '20201221'
  environment:
    TZ: Asia/Tokyo
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::b1ec0be3-01c8-438a-817f-710e84866464

package:
  patterns:
    - dist/**
