service: app-server
frameworkVersion: '2'

functions:
  index:
    handler: dist/index.handler
    events:
      - httpApi: "GET /"

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: us-east-1
  memorySize: 128
  timeout: 10
  logRetentionInDays: 30
  deploymentBucket: mryhryki-temp
  versionFunctions: false
  lambdaHashingVersion: '20201221'
  environment:
    TZ: Asia/Tokyo
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:ListBucket
            - s3:GetObject
            - s3:PutObject
            - s3:RestoreObject
          Resource:
            - arn:aws:s3:::mryhryki-temp
            - arn:aws:s3:::mryhryki-temp/*

package:
  patterns:
    - dist/**
